import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'..');
const server=createServer(async(req,res)=>{try{const path=resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!path.startsWith(root+'/')){res.writeHead(403);res.end();return;}res.setHeader('Content-Type',extname(path)==='.js'?'text/javascript':'text/html');res.end(await readFile(path));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;
try{
 browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1150,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${server.address().port}/demo/index.html`);
 const card=page.locator('printer-card'),editor=page.locator('printer-card-editor');
 await card.locator('h2').waitFor();
 assert.equal(await card.locator('.toner').count(),4);
 assert.equal(await card.locator('.warning').count(),1);
 assert.equal(await editor.locator('[data-entity]').count(),10);
 assert.equal(await editor.locator('datalist option').count(),10);
 await page.screenshot({path:resolve(root,'demo/preview.png'),fullPage:false});
 await page.selectOption('#state','Ausdruck');
 assert.equal(await card.locator('.paper').count(),1);
 await editor.locator('[data-key="animation"]').uncheck();
 assert.equal(await card.locator('.paper').count(),0);
 await page.selectOption('#state','No paper Tray 2');
 assert.equal(await card.locator('.status').textContent(),'Kein Papier · Fach 2');
 await editor.locator('#entity-cyan').fill('');await editor.locator('#entity-cyan').press('Tab');
 assert.equal(await card.locator('.toner').count(),3);
 await editor.locator('#entity-cyan').fill('sensor.nonexistent');await editor.locator('#entity-cyan').press('Tab');
 assert.match(await card.locator('.note').textContent(),/sensor.nonexistent/);
 assert.equal(await card.locator('.unknown .pct').textContent(),'—');
 await editor.locator('#entity-cyan').fill('sensor.demo_cyan');await editor.locator('#entity-cyan').press('Tab');
 await editor.locator('summary').click();
 await editor.locator('#pattern-ready').fill('=online');await editor.locator('#pattern-ready').press('Tab');
 await page.selectOption('#state','Bereit');assert.equal(await card.locator('.status').textContent(),'Bereit');
 assert.match(await card.locator('ha-card').getAttribute('style'),/#ef9a23/);
 await editor.locator('#reset').click();assert.match(await card.locator('ha-card').getAttribute('style'),/#4caf50/);
 await card.locator('.toner').first().click();assert.match(await page.locator('#events').textContent(),/sensor.demo_cyan/);
 await editor.locator('#name').fill('<img src=x onerror=alert(1)>');await editor.locator('#name').press('Tab');
 assert.equal(await card.locator('img').count(),0);assert.equal(await card.locator('h2').textContent(),'<img src=x onerror=alert(1)>');
 await editor.locator('#name').fill('Bürodrucker');await editor.locator('#name').press('Tab');
 await editor.locator('#language').selectOption('en');assert.equal(await card.locator('.status').textContent(),'Ready');
 await page.locator('#missing').click();assert.equal(await card.locator('.unknown .pct').textContent(),'—');
 await page.setViewportSize({width:320,height:900});await page.locator('#theme').click();
 assert.ok(await card.evaluate(el=>el.scrollWidth<=el.clientWidth));
 await page.emulateMedia({reducedMotion:'reduce'});
 await editor.locator('[data-key="animation"]').check();await page.selectOption('#state','Ausdruck');
 assert.equal(await card.locator('.paper').evaluate(el=>getComputedStyle(el).animationName),'none');
 await page.evaluate(()=>window.scrollTo(0,0));
 await page.screenshot({path:resolve(root,'demo/preview-mobile-dark.png'),fullPage:false});
 assert.deepEqual(errors,[]);
 console.log('PASS: built bundle, editor 10 entity fields, datalist, mappings/reset, removals/missing data, animations, more-info, HTML escaping, language, mobile, dark theme, reduced motion; no browser errors.');
}finally{await browser?.close();server.close();}
