export const CARD_STYLE = `
:host{display:block;color:var(--primary-text-color,#202932);font-family:var(--paper-font-body1_-_font-family,system-ui,sans-serif)}
*{box-sizing:border-box}ha-card{display:block;padding:20px;border-radius:var(--ha-card-border-radius,18px);background:var(--ha-card-background,var(--card-background-color,#fff));border:1px solid var(--divider-color,#dce2e8);height:100%;overflow:hidden}
header{display:flex;align-items:center;gap:16px}h2{font-size:21px;line-height:1.3;margin:0;overflow-wrap:anywhere;font-weight:600}.printer{width:56px;height:56px;flex-shrink:0;color:var(--status-color)}
.status{color:var(--status-color);font-weight:600;text-align:center;margin:12px 0 0;overflow-wrap:anywhere}.raw{text-align:center;font-size:12px;color:var(--secondary-text-color,#687481);margin:4px 0 0;overflow-wrap:anywhere}
button{font:inherit;color:inherit;background:none;border:0;padding:0;cursor:pointer}button:focus-visible{outline:2px solid var(--primary-color,#008ac2);outline-offset:4px;border-radius:6px}.head-button{display:flex;align-items:center;gap:16px;text-align:left;width:100%}
.toners{display:flex;justify-content:space-evenly;gap:12px;margin:25px 0 20px}.toner{display:flex;flex-direction:column;align-items:center;gap:7px;min-width:0}.letter{font-weight:800;font-size:16px;color:var(--toner)}.cartridge{position:relative;width:44px;height:100px;border:2px solid var(--secondary-text-color,#75808b);border-radius:7px;background:var(--divider-color,#e5e9ed);overflow:hidden}.fill{position:absolute;bottom:0;left:0;right:0;background:var(--toner);transition:height .6s ease}.shine{position:absolute;top:9px;left:6px;right:6px;height:3px;background:#ffffff60;border-radius:3px}.pct{font-size:15px;font-weight:600}.warning .cartridge{border-color:var(--error-color,#db4437)}.warning .pct,.low{color:var(--error-color,#db4437)}.low{font-size:11px;min-height:15px}.unknown .cartridge{background:repeating-linear-gradient(135deg,transparent,transparent 5px,#8882 5px,#8882 10px)}
.drum{border-top:1px solid var(--divider-color,#ddd);padding-top:15px;display:flex;justify-content:space-between;gap:12px;align-items:center;width:100%;text-align:left}.drum span{font-size:13px;color:var(--secondary-text-color,#687481)}.drum strong{overflow-wrap:anywhere;text-align:right}.stats{margin-top:18px;border-top:1px solid var(--divider-color,#ddd);padding-top:15px;display:grid;grid-template-columns:repeat(auto-fit,minmax(72px,1fr));gap:14px 8px}.stat{min-width:0}.stat span{display:block;font-size:11px;color:var(--secondary-text-color,#687481)}.stat strong{display:block;font-size:17px;margin-top:5px;overflow-wrap:anywhere}.note{font-size:13px;color:var(--secondary-text-color,#687481);margin:16px 0 0;overflow-wrap:anywhere}
.paper-slot{height:34px;overflow:hidden;display:flex;justify-content:center;margin-top:6px}.paper{height:25px;width:34px;border:1px solid #aeb6bf;background:white;border-radius:2px;animation:feed 1.3s infinite ease-in-out}.paper:after{content:'';display:block;width:20px;height:2px;background:#bbb;margin:6px auto;box-shadow:0 5px #bbb}.printing{animation:pulse 1s infinite ease-in-out}.warning.animate{animation:warn 1.4s infinite ease-in-out}
@keyframes pulse{50%{transform:scale(1.08)}}@keyframes feed{0%{transform:translateY(-8px);opacity:.3}50%{opacity:1}100%{transform:translateY(15px);opacity:0}}@keyframes warn{50%{opacity:.55}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important}}
@media(max-width:350px){ha-card{padding:14px}h2{font-size:18px}.toners{gap:8px}.cartridge{width:38px}.stats{grid-template-columns:repeat(2,minmax(0,1fr))}}
`;
export const EDITOR_STYLE = `
:host{display:block;font-family:system-ui,sans-serif;color:var(--primary-text-color,#202932)}*{box-sizing:border-box}fieldset{border:1px solid var(--divider-color,#ccc);border-radius:10px;margin:16px 0;padding:14px}legend{font-weight:600}label{display:block;font-size:13px;margin:12px 0 5px}input:not([type=checkbox]),select,textarea{display:block;width:100%;border:1px solid var(--divider-color,#aaa);border-radius:6px;background:var(--card-background-color,#fff);color:inherit;font:inherit;padding:10px}textarea{min-height:90px;resize:vertical}input:focus,textarea:focus,select:focus{outline:2px solid var(--primary-color,#008ac2)}.check{display:flex;gap:8px;align-items:center}p,small{line-height:1.5;color:var(--secondary-text-color,#667)}.error{color:var(--error-color,#c33)}button{padding:8px 12px;cursor:pointer;border-radius:6px;border:1px solid var(--divider-color,#aaa);background:var(--card-background-color,#fff);color:inherit}summary{cursor:pointer;padding:8px 0;font-weight:600}
`;
